- name: Install CrowdSec on Ubuntu
  hosts: rocky
  become: true

  tasks:
    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Download CrowdSec installation script
      shell: curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh

    - name: Install CrowdSec
      apt:
        deb: /tmp/script.deb.sh
        state: present
      become: true
